#!/bin/sh
set -e

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
cd "$SCRIPT_DIR"

# Required settings.
exp_name=sqdiffuse_train                # Experiment name. Outputs are saved under output_dir/exp_name.
dataset_folder=/path/to/cdfgen_dataset  # Training dataset folder generated by data_tools.
output_dir=results/train_sqdiffuse      # Root folder for checkpoints, logs, and validation outputs.
ae_pth=checkpoints/sqvae.pth            # Trained SQVAE checkpoint used by SQDiffuse.

# Common training settings.
n_gpu=1                       # Number of GPUs for torchrun.
batch_size=1                  # Batch size per GPU.
gradient_accumulate_steps=1   # Gradient accumulation steps.
lr=0.0001                     # Learning rate.
warmup_epochs=1               # Learning-rate warmup epochs. Ignored when use_const_lr=1.
res=4096                      # Number of latent tokens for SQDiffuse training.

# Optional settings.
n_nodes=1                                      # Number of nodes. Keep 1 for single-node training.
ae_config=squadgen/network/config/sqvae_geomae.yaml  # SQVAE + Geometry AE config file.
model_config=squadgen/network/config/sqdiffuse.yaml # SQDiffuse config file.
resume_from_another=                          # Optional SQDiffuse checkpoint to resume or initialize from.
val_num=2                                     # Number of validation samples.
report_to=tensorboard                         # Logging backend: tensorboard or wandb. For wandb, configure project settings in squadgen/util/logger.py first.

effective_batch_size=$((batch_size * gradient_accumulate_steps * n_gpu * n_nodes))
echo "effective_batch_size=${effective_batch_size}"

mkdir -p "$output_dir"

torchrun --nproc_per_node="$n_gpu" -m squadgen.main_sqdiffuse \
    --name="$exp_name" \
    --batch_size="$batch_size" \
    --continue_training=1 \
    --epochs=600 \
    --dataset_folder="$dataset_folder" \
    --output_dir="$output_dir" \
    --report_to="$report_to" \
    --model_config="$model_config" \
    --accum_iter="$gradient_accumulate_steps" \
    --lr="$lr" \
    --val_num="$val_num" \
    --val_model_per_epoch=5 \
    --num_workers=-1 \
    --warmup_epochs="$warmup_epochs" \
    --ae_pth="$ae_pth" \
    --ae_config="$ae_config" \
    --is_mode=1 \
    --training_data_repeat_times=1 \
    --resume_from_another="$resume_from_another" \
    --mix_precision=1 \
    --mix_precision_dtype=bf16 \
    --drop_prob=0.1 \
    --sit_path_type=Linear \
    --sit_prediction=velocity \
    --sit_loss_weight=None \
    --use_const_lr=1 \
    --clip_grad=1 \
    --labeling_fn=labeling_all.json \
    --is_render_image=1 \
    --dist_hook=1 \
    --save_model_per_epoch=1 \
    --res="$res" \
    --training_epoch_len=200000 \
    --val_dataset_type_list=test,train
