#!/bin/sh
set -e

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
cd "$SCRIPT_DIR"

# Required settings.
exp_name=sqvae_train                  # Experiment name. Outputs are saved under output_dir/exp_name.
dataset_folder=/path/to/cdfgen_dataset # Training dataset folder generated by data_tools.
output_dir=results/train_sqvae         # Root folder for checkpoints, logs, and validation outputs.
pretrained_geom_vae_pth=checkpoints/geometry_ae.pth # Geometry AE checkpoint used to initialize SQVAE training.

# Common training settings.
n_gpu=1                       # Number of GPUs for torchrun.
batch_size=16                 # Batch size per GPU.
gradient_accumulate_steps=1   # Gradient accumulation steps.
lr=0.0001                     # Learning rate.
warmup_epochs=5               # Learning-rate warmup epochs.
res=-1                        # Number of latent tokens. Use -1 to keep the config default.

# Optional settings.
n_nodes=1                                   # Number of nodes. Keep 1 for single-node training.
vae_config=squadgen/network/config/sqvae_geomae.yaml # SQVAE + Geometry AE config file.
resume_from_another=                       # Optional checkpoint to resume or initialize from.
val_num=4                                  # Number of validation samples.
n_sample_surface_query=8192                # Number of query points for training reconstruction loss.
report_to=tensorboard                      # Logging backend: tensorboard or wandb. For wandb, configure project settings in squadgen/util/logger.py first.

effective_batch_size=$((batch_size * gradient_accumulate_steps * n_gpu * n_nodes))
echo "effective_batch_size=${effective_batch_size}"

mkdir -p "$output_dir"

torchrun --nproc_per_node="$n_gpu" -m squadgen.main_ae \
    --name="$exp_name" \
    --batch_size="$batch_size" \
    --continue_training=1 \
    --epochs=600 \
    --dataset_folder="$dataset_folder" \
    --output_dir="$output_dir" \
    --report_to="$report_to" \
    --model_config="$vae_config" \
    --accum_iter="$gradient_accumulate_steps" \
    --lr="$lr" \
    --val_num="$val_num" \
    --val_model_per_epoch=1 \
    --num_workers=-1 \
    --warmup_epochs="$warmup_epochs" \
    --pretrained_geom_vae_pth="$pretrained_geom_vae_pth" \
    --use_geom_cond_mean=1 \
    --training_data_repeat_times=1 \
    --resume_from_another="$resume_from_another" \
    --mix_precision=1 \
    --mix_precision_dtype=bf16 \
    --clip_grad=1 \
    --labeling_fn=labeling_all.json \
    --training_epoch_len=450000 \
    --res="$res" \
    --n_sample_surface_query="$n_sample_surface_query" \
    --dist_hook=0 \
    --is_render_image=1 \
    --val_dataset_type_list=test,train